name = "s"
type = "webpack"
account_id = "1c5f0bb50c92188dd028fa501cb54b88"
workers_dev = true

# [vars]
# B=''
# TOKEN="1392892828:AAFkhbvyfgDDOAd6BaGju2wC1B8PaGza6Pc"

# [site]
# bucket = "./public"
# entry-point = "./"

[[kv-namespaces]]
binding = "LINKS"
id = "8e32432036fe4eca9a4ea84a8d84d829"